### PR TITLE
Fix issue #18

### PR DESCRIPTION
**Pull request by shakib609**
Update readme to include correct rails version #18

### CODE REVIEW

**Comment by kathyonu** [comment]
Nice catch, thank you.

**Comment by shakib609** [comment]
Welcome! Glad to help.
Please **CLOSE** the issue.

**Comment by bishisht** [comment]
@shakib609 Could you please check other issues if you have time. Thanks.

**Comment by shakib609** [comment]
@bishisht I will try my best. I am new to rails though.

**Pull request merged**
